[[overview]]
== 概要

このドキュメントの目的は、テストを書くプログラマや機能を拡張する開発者や
駆動部分の開発者ならびにビルドツールやIDEのベンダーの方々に、包括的な参考資料を提供することです。

ifdef::backend-html5[このドキュメントは link:https://junit.org/junit5/docs/{docs-version}/user-guide/index.pdf[PDF] でも利用可能です。]


[TIP]
.Translations
====
このドキュメントは http://sjyuan.cc/junit5/user-guide-cn/[簡体字中国語] と
https://udzuki.jp/public/junit5-user-guide-ja[日本語] でも利用可能です。
====

[[overview-what-is-junit-5]]
=== JUnit 5とは？

これまでのバージョンのJUnitとは異なり、JUnit 5は、
3つの異なるサブプロジェクトの様々なモジュールで構成されています。

**JUnit 5 = _JUnit Platform_ + _JUnit Jupiter_ + _JUnit Vintage_**

**JUnit Platform** は、JVM上で <<launcher-api,テスティングフレームワークを起動させる>>
ための基礎としての機能を果たします。
また、プラットフォーム上で動作するテスティングフレームワークを開発するための
`{TestEngine}` APIを定義しています。
さらに、コマンドラインからプラットフォームを立ち上たり、
<<running-tests-build-gradle,Gradle>> と　<<running-tests-build-maven,Maven>>
のためのプラグインを構築するために
<<running-tests-console-launcher,コンソールラウンチャー>>を提供します。
また、プラットフォーム上であらゆる `TestEngine` を実行するために、
<<running-tests-junit-platform-runner,JUnit 4ベースのRuunner>> も提供します。

**JUnit Jupiter** は、新しい <<writing-tests,プログラミングモデル>> と <<extensions,拡張モデル>>
の組み合わせで、JUnit 5でテストを書いたり、拡張するためのものです。
Jupiterのサブプロジェクトは、プラットフォーム上でJupiterベースのテストを
実行するための `TestEngine` を提供します。

**JUnit Vintage** は、
プラットフォーム上でJUnit 3とJUnit 4ベースのテストを実行するための
`TestEngine` を提供します。

[[overview-java-versions]]
=== サポートしているJavaのバージョン

JUnit 5は実行時にJava 8（もしくは、それ以上）を必要とします。
しかしながら、以前のバージョンのJDKでコンパイルされたコードもテスト可能です。

[[overview-getting-help]]
=== ヘルプ

JUnit 5に関連した質問は {StackOverflow} で尋ねるか、
{Gitter} で私たちに話しかけてください。
