[[running-tests]]
== テストの実行

[[running-tests-ide]]
=== IDEサポート

[[running-tests-ide-intellij-idea]]
==== IntelliJ IDEA

IntelliJ IDEAは、バージョン 2016.2 以降、JUnit Platform上でのテスト実行をサポートしています。
詳細については、 https://blog.jetbrains.com/idea/2016/08/using-junit-5-in-intellij-idea/[IntelliJ IDEAブログの記事] をご覧ください。
しかしながら、2017.3 以降の新しいバージョンのIDEAを使うことをお薦めします。
というのも、これらの新しいバージョンのIDEAは、プロジェクト内で使われているAPIバージョンに応じて
次のJARを自動でダウンロードしてくれるからです：
`junit-platform-launcher` ・ `junit-jupiter-engine` ・ `junit-vintage-engine`

WARNING: IDEA 2017.3より前のIntelliJ IDEAは、
特定のバージョンのJUnit 5をバンドルします。
そのため、新しいバージョンのJUnit Jupiterを使いたい場合、
IDE内でのテスト実行はバージョンの衝突によって失敗する恐れがあります。
そのような場合、ItelliJ IDEAにバンドルされたものではない新しいJUnit 5を
使うために下の説明に従ってください。

異なるJUnit 5のバージョン（例えば、 {jupiter-version} ）を使うには、
対応するバージョンの `junit-platform-launcher` と `junit-jupiter-engine` 、
`junit-vintage-engine` のJARをクラスパスに含める必要があるかもしれません。

.追加のGradleの依存関係

[source,groovy]
[subs=attributes+]
----
// Only needed to run tests in a version of IntelliJ IDEA that bundles older versions
testRuntime("org.junit.platform:junit-platform-launcher:{platform-version}")
testRuntime("org.junit.jupiter:junit-jupiter-engine:{jupiter-version}")
testRuntime("org.junit.vintage:junit-vintage-engine:{vintage-version}")
----

.追加のMavenの依存関係
[source,xml]
[subs=attributes+]
----
<!-- Only needed to run tests in a version of IntelliJ IDEA that bundles older versions -->
<dependency>
    <groupId>org.junit.platform</groupId>
    <artifactId>junit-platform-launcher</artifactId>
    <version>{platform-version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <version>{jupiter-version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.junit.vintage</groupId>
    <artifactId>junit-vintage-engine</artifactId>
    <version>{vintage-version}</version>
    <scope>test</scope>
</dependency>
----

[[running-tests-ide-eclipse]]
==== Eclipse

Eclipse IDEは、Eclipse Oxygen.1a (4.7.1a)から
JUnit Platformサポートを提供しています。

EclipseでJUnit 5を使うためのさらなる情報については、
https://www.eclipse.org/eclipse/news/4.7.1a/#junit-5-support[Eclipse Project Oxygen.1a (4.7.1a) - New and Noteworthy]
記事にある公式な _Eclipse support for JUnit 5_ の章をご覧ください。

[[running-tests-ide-other]]
==== 他のIDE

この記事を書いている時点では、IDEAとEclipseを除き、IDE内でJUnit Platform上のテスト実行を
直接サポートしているIDEはありません。しかしながら、いまいまでも自身のIDEでJUnit 5を
試すことができるように、JUnitチームは2つの仲介的な解決法を提供しています。
それは <<running-tests-console-launcher, コンソールラウンチャー>> を手動で使うか、
<<running-tests-junit-platform-runner,JUnit 4ベースのランナー>> でテストを実行することです。

[[running-tests-build]]
=== ビルドサポート

[[running-tests-build-gradle]]
==== Gradle

https://docs.gradle.org/4.6/release-notes.html[バージョン 4.6] から、
GradleはJUnit Platform上でのテスト実行への
https://docs.gradle.org/current/userguide/java_testing.html#using_junit5[ネイティブ・サポート]
を提供しています。
それを有効化するためには、 `build.gradle` 内の `test` タスク宣言で
`useJUnitPlatform()` を指定するだけです。

[source,java]
----
test {
    useJUnitPlatform()
}
----

タグやエンジンによるフィルタリングもサポートされています：

[source,java]
----
test {
    useJUnitPlatform {
        includeTags 'fast', 'smoke & feature-a'
        // excludeTags 'slow', 'ci'
        includeEngines 'junit-jupiter'
        // excludeEngines 'junit-vintage'
    }
}
----

オプションの包括的なリストについては、
https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_test[Gradleの公式ドキュメント]
を参照してください。

[WARNING]
.JUnit Platform Gradleプラグインは廃止
====
JUnitチームによって開発された非常に初歩的な `junit-platform-gradle-plugin` は、
JUnit Platform 1.2で非推奨になり、1.3で廃止されました。
Gradleの標準的な `test` タスクに移行してください。
====

[[running-tests-build-gradle-config-params]]
===== 設定パラメータ

標準的なGralde `test` タスクは現在、テスト発見や実行に役立つJUnit Platform
<<running-tests-config-params, 設定パラメータ>> を設定するための専用DSLを提供していません。
しかしながら、（下に示すように）システムプロパティや
`junit-platform.properties` を通して、ビルドスクリプト内で設定パラメータを提供できます。

[source,java]
----
test {
    // ...
    systemProperty 'junit.jupiter.conditions.deactivate', '*'
    systemProperties = [
        'junit.jupiter.extensions.autodetection.enabled': 'true',
        'junit.jupiter.testinstance.lifecycle.default': 'per_class'
    ]
    // ...
}
----

[[running-tests-build-gradle-engines-configure]]
===== テストエンジンの設定

テストを実行するには、 `TestEngine` 実装をクラスパス上に配置する必要があります。

JUnit Jupiterベースのテストへのサポートを設定するには、
次のように、 `testCompile` の依存関係にJUnit Jupiter APIと、
`testRuntime` の依存関係にJUnit Jupiter `TestEngine` 実装を設定する必要があります。

[source,java]
[subs=attributes+]
----
dependencies {
    testCompile("org.junit.jupiter:junit-jupiter-api:{jupiter-version}")
    testRuntime("org.junit.jupiter:junit-jupiter-engine:{jupiter-version}")
}

----

JUnit Platformは、次のように、 `testCompile` の依存関係にJUnit 4と、
`testRuntime` の依存関係にJUnit Vintage `TestEngine` 実装を設定することで、
JUnit 4ベースのテストを実行することができます。

[source,java]
[subs=attributes+]
----
dependencies {
    testCompile("junit:junit:{junit4-version}")
    testRuntime("org.junit.vintage:junit-vintage-engine:{vintage-version}")
}
----

[[running-tests-build-gradle-logging]]
===== ログの設定（オプション）

JUnitは、 _JUL_ で知られている `java.util.logging` パッケージ内の
Java Logging APIを使って、警告とデバッグ情報を排出しています。
設定オプションについては、 `{LogManager}` の公式ドキュメントを参照してください。

その他に、ログメッセージを {Log4J} や {Logback} といった
他のロギングフレームワークにログメッセージをリダイレクトすることもできます。
`{LogManager}` の カスタム実装を提供しているロギングフレームワークを使うには、
`java.util.logging.manager` システムプロパティに、使う `{LogManager}`実装の
_完全修飾クラス名_ を設定してください。
下の例では、Log4j 2.xの設定方法を示しています
（詳細については、 {Log4j_JDK_Logging_Adapter} をご覧ください）。

[source,java]
----
test {
    systemProperty 'java.util.logging.manager', 'org.apache.logging.log4j.jul.LogManager'
}
----

他のロギングフレームワークは、 `java.util.logging` を使ってログされた
メッセージをリダイレクトするための他の方法を提供しています。
例えば、 {Logback} では、
実行時のクラスパスに依存関係を追加することで、
https://www.slf4j.org/legacy.html#jul-to-slf4j[JULからSLF4Jへの橋渡し] を使うことができます。

[[running-tests-build-maven]]
==== Maven

NOTE: JUnitチームによって独自に開発されていた、
カスタム `junit-platform-surefire-provider` は非推奨となり、
JUnit Platform 1.4で削除される予定です。
代わりに、Maven Surefireのネイティブサポートを使用してください。

https://issues.apache.org/jira/browse/SUREFIRE-1330[version 2.22.0]
から、Maven SurefireはJUnit Platform上でテスト実行するための
http://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html[ネイティブ・サポート]
を提供しています。
`{junit5-jupiter-starter-maven}` プロジェクト内の `pom.xml` は
使用方法を説明しており、あなたのMavenビルドを
設定するための開始点として用いることができます。

[[running-tests-build-maven-engines-configure]]
===== テストエンジンの設定

Maven Surefireでテストを実行するには、
少なくとも1つの `TestEngine` 実装をテストのクラスパスに加える必要があります。

JUnit Jupiterベースのテストへのサポートを設定するには、
JUnit Jupiter APIとJUnit Jupiter `TestEngine` 実装上に
次のものと似たような `test` スコープの依存関係を設定してください。

[source,xml]
[subs=attributes+]
----
<build>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>{surefire-version}</version>
        </plugin>
    </plugins>
</build>
...
<dependencies>
    ...
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>{jupiter-version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <version>{jupiter-version}</version>
        <scope>test</scope>
    </dependency>
    ...
</dependencies>
...
----

JUnit 4とJUnit Vintage `TestEngine` 実装上に
次のような `test` スコープの依存関係を設定することで、
Maven SurefireはJUnit 4ベースのテストをJupiterテストと一緒に実行できます。

[source,xml]
[subs=attributes+]
----
...
<build>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>{surefire-version}</version>
        </plugin>
    </plugins>
</build>
...
<dependencies>
    ...
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>{junit4-version}</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.junit.vintage</groupId>
        <artifactId>junit-vintage-engine</artifactId>
        <version>{vintage-version}</version>
        <scope>test</scope>
    </dependency>
    ...
</dependencies>
...
----

[[running-tests-build-maven-filter-test-class-names]]
===== テストクラス名によるフィルタリング

Maven Surefire Pluginは、
次のパターンにマッチする完全修飾名を持つテストクラスをスキャンします。

- `+**/Test*.java+`
- `+**/*Test.java+`
- `+**/*Tests.java+`
- `+**/*TestCase.java+`

さらに、全てのネストされたクラス（静的なメンバークラスも含む）はデフォルトで除外されます。

しかしながら、このデフォルトの振る舞いは、 `pom.xml` ファイル内に
明示的に `include` と `exclude` の規則を設定することで上書きできます。
例えば、Maven Surefireに静的なメンバークラスを除外させないためには、
次のように除外規則を上書きします。

[source,xml]
[subs=attributes+]
._Maven Surefireの除外規則の上書き_
----
 ...
<build>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>{surefire-version}</version>
            <configuration>
                <excludes>
                    <exclude/>
                </excludes>
            </configuration>
        </plugin>
    </plugins>
</build>
...
----

詳細については、Maven Surefireの
https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html[テストの包含と除外]
のドキュメントをご覧ください。

[[running-tests-build-maven-filter-tags]]
===== タグによるフィルタリング

次の設定プロパティを用いることでタグ、
または <<running-tests-tag-expressions, タグ表現>> によって
テストをフィルターすることができます。

- _タグ_ 、または _タグ表現_ を包含するには、 `groups` を使ってください。
- _タグ_ 、または _タグ表現_ を除外するには、 `excludedGroups` を使ってください。

[source,xml]
[subs=attributes+]
----
...
<build>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>{surefire-version}</version>
            <configuration>
                <groups>acceptance | !feature-a</groups>
                <excludedGroups>integration, regression</excludedGroups>
            </configuration>
        </plugin>
    </plugins>
</build>
...
----

[[running-tests-build-maven-config-params]]
===== 設定パラメータ

`configurationParameters` プロパティを宣言し、
（下に示すように）Java `Properties` ファイル構文を使うか
`junit-platform.properties` ファイルを通してキーバリューペアを提供することで、
テスト探索と実行に影響を与えるJUnit Platform <<running-tests-config-params, 設定パラメータ>> をセットすることができます。

[source,xml]
[subs=attributes+]
----
...
<build>
    <plugins>
        ...
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>{surefire-version}</version>
            <configuration>
                <properties>
                    <configurationParameters>
                        junit.jupiter.conditions.deactivate = *
                        junit.jupiter.extensions.autodetection.enabled = true
                        junit.jupiter.testinstance.lifecycle.default = per_class
                    </configurationParameters>
                </properties>
            </configuration>
        </plugin>
    </plugins>
</build>
...
----

[[running-tests-build-ant]]
==== Ant

https://ant.apache.org/[Ant] のバージョン `1.10.3` から、
新しい https://ant.apache.org/manual/Tasks/junitlauncher.html[`junitlauncher`] タスクが
導入され、JUnit Platform上でのテスト実行がネイティブサポートされました。
`junitlauncher` タスクは単独で、JUnit Platformを起動して
選択されたテストコレクションをPlatformに渡します。
JUnit Platformはその後、テストの探索と実行を登録されたテストエンジンに委譲します。

`junitlauncher` タスクは、
https://ant.apache.org/manual/Types/resources.html#collection[リソースコレクション]
といったネイティブなAnt構造にできる限り密接に連携しています。
これにより、ユーザがテストエンジンに実行してほしいテストを選択する際、
他多数のコアなAntタスクと比べても一貫して自然な感覚を与えています。

NOTE: Ant 1.10.3にある `junitlauncher` タスクのバージョンは、
JUnit Platformを起動するための基本的で最小のサポートを提供しています。
追加的な機能強化（分離したJVMへのテスト分岐のサポートも含む）が
次のAntのリリースで利用可能になる予定です。


`{junit5-jupiter-starter-ant}` プロジェクト内の `build.xml` は、
タスクの利用方法を示しており、開始点として使うことができます。

===== 基本的な使い方

次の例は、 `junitlauncher` タスクに1つのテストクラス
（つまり、 `org.myapp.test.MyFirstJUnit5Test` ）を選ぶための設定方法を示しています。

[source,xml]
----
<path id="test.classpath">
    <!-- The location where you have your compiled classes -->
    <pathelement location="${build.classes.dir}" />
</path>

<!-- ... -->

<junitlauncher>
    <classpath refid="test.classpath" />
    <test name="org.myapp.test.MyFirstJUnit5Test" />
</junitlauncher>
----

`test` 要素を使うことで、実行したいテストを1つ選択できます。
`classpath` 要素を使うことで、JUnit Platformを起動するために使うクラスパスを指定できます。
このクラスパスは、実行の一部であるテストクラスの場所を特定するためにも使われます。

次の例は、複数の箇所からテストクラスを選ぶための
`junitlauncher` タスクの設定方法を示しています。

[source,xml]
----
<path id="test.classpath">
    <!-- The location where you have your compiled classes -->
    <pathelement location="${build.classes.dir}" />
</path>
....
<junitlauncher>
    <classpath refid="test.classpath" />
    <testclasses outputdir="${output.dir}">
        <fileset dir="${build.classes.dir}">
            <include name="org/example/**/demo/**/" />
        </fileset>
        <fileset dir="${some.other.dir}">
            <include name="org/myapp/**/" />
        </fileset>
    </testclasses>
</junitlauncher>
----

上の例では、 `testclasses` 要素によって
異なる位置にある複数のテストクラスを選択しています。

用法と設定オプションのさらなる詳細については、
https://ant.apache.org/manual/Tasks/junitlauncher.html[`junitlauncher` タスク]
に関するAntの公式ドキュメントをご覧ください。

[[running-tests-console-launcher]]
=== コンソールラウンチャー

`{ConsoleLauncher}` はコマンドラインによるJavaアプリケーションで、
JUnit Platformをコンソールから起動できます。
例えば、JUnit VintageとJUnit Jupiterテストを実行し、
テストの実行結果をコンソールに出力します。

全ての依存関係が含まれた実行可能な `junit-platform-console-standalone-{platform-version}.jar` は、
Mavenセントラルレポジトリ内の
https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone[junit-platform-console-standalone] ディレクトリ以下に公開されています。
スタンドアローンな `ConsoleLauncher` は次のように https://docs.oracle.com/javase/tutorial/deployment/jar/run.html[実行]できます。

`java -jar junit-platform-console-standalone-1.2.0.jar <<<running-tests-console-launcher-options, Options>>>`

これが出力の例です。

[source]
----
├─ JUnit Vintage
│  └─ example.JUnit4Tests
│     └─ standardJUnit4Test ✔
└─ JUnit Jupiter
   ├─ StandardTests
   │  ├─ succeedingTest() ✔
   │  └─ skippedTest() ↷ for demonstration purposes
   └─ A special test case
      ├─ Custom test name containing spaces ✔
      ├─ ╯°□°）╯ ✔
      └─ 😱 ✔

Test run finished after 64 ms
[         5 containers found      ]
[         0 containers skipped    ]
[         5 containers started    ]
[         0 containers aborted    ]
[         5 containers successful ]
[         0 containers failed     ]
[         6 tests found           ]
[         1 tests skipped         ]
[         5 tests started         ]
[         0 tests aborted         ]
[         5 tests successful      ]
[         0 tests failed          ]
----

.終了コード
NOTE: `{ConsoleLauncher}` は、いずれかのコンテナまたはテストが失敗した場合は
ステータスコード `1` で終了します。
もしテストが1つも発見されず、 `--fail-if-no-tests` コマンドライン・オプションが
供給された時はステータスコード `2` で終了します。
そのどれでもない場合、ステータスコードは `0` となります。

[[running-tests-console-launcher-options]]
==== オプション

[source]
----

使用方法：ConsoleLauncher  [-h] [--disable-ansi-colors] [--fail-if-no-tests] [--scan-modules]
                          [--scan-classpath[=PATH[;|:PATH...]]]... [--details=MODE]
                          [--details-theme=THEME] [--reports-dir=DIR]
                          [--config=KEY=VALUE]... [--exclude-package=PKG]...
                          [--include-package=PKG]... [-c=CLASS]... [-cp=PATH[;|:PATH...]]...
                          [-d=DIR]... [-e=ID]... [-E=ID]... [-f=FILE]... [-m=NAME]...
                          [-n=PATTERN]... [-N=PATTERN]... [-o=NAME]... [-p=PKG]...
                          [-r=RESOURCE]... [-t=TAG]... [-T=TAG]... [-u=URI]...

コンソールからJUnit Platformを起動する。
 -h, --help                  ヘルプ情報を表示します。
     --disable-ansi-colors   出力でANSIカラーを無効化します。（全てのターミナルではサポートされていません。）
     --details=MODE          テスト実行時の出力詳細モードを選択します。
                                次のうち、どれか1つを使います: none, summary, flat, tree, verbose。
                                'none'が選択された場合、要旨とテスト失敗のみが表示されます。
                                （デフォルト：tree）
     --details-theme=THEME   テスト実行時の出力詳細ツリーのテーマを選択します。
                                次のうち、どれか1つを使います: ascii, unicode。
                                （デフォルト：unicode）
     -cp, --classpath, --class-path=PATH[;|:PATH...]
                             追加的なクラスパスエントリを提供します。 -- 例えば、
                                テストエンジンとその依存関係を追加できます。このオプションは繰り返し可能です。
     --fail-if-not-tests     もしテストが見つからない場合は、失敗して終了ステータスコード 2 を返します。
     --reports-dir=DIR       特定のローカルディレクトリへのレポート出力を有効化します。
                                （ディレクトリが存在しない場合は生成されます。）
     --scan-modules          実験的：テスト発見のために全ての解決済みモジュールをスキャンします。
 -o, --select-module=NAME    実験的：テスト発見のためのモジュールを選択します。
                                このオプションは繰り返し可能です。
     --scan-class-path, --scan-classpath[=PATH[;|:PATH...]]
                             クラスパス、または明示的なクラスパスのルート上の全てのディレクトリをスキャン
                                します。引数がない場合、システムクラスパスと-cp（ディレクトリと
                                JARファイル）を通して供給された追加的なクラスパスエントリ上のディレクトリ
                                のみがスキャンされます。クラスパス上にない明示的なクラスパスのルートは、
                                静かに無視されます。このオプションは繰り返し可能です。
 -u, --select-uri=URI        テスト発見のためのURIを選択します。このオプションは繰り返し可能です。
 -f, --select-file=FILE      テスト発見のためのファイルを選択します。このオプションは繰り返し可能です。
 -d, --select-directory=DIR  テスト発見のためのディレクトリを選択します。このオプションは繰り返し可能です。
 -p, --select-package=PKG    テスト発見のためのパッケージを選択します。このオプションは繰り返し可能です。
 -c, --select-class=CLASS    テスト発見のためのクラスを選択します。このオプションは繰り返し可能です。
 -m, --select-method=NAME    テスト発見のためのメソッドを選択します。このオプションは繰り返し可能です。
 -r, --select-resource=RESOURCE
                             テスト発見のためのクラスパス・リソースを選択します。
                                このオプションは繰り返し可能です。
 -n, --include-classname=PATTERN
                             完全修飾名がマッチするクラスのみを内包するための正規表現を提供します。
                                不要なクラス読み込みを避けるために、デフォルトのパターンは、クラス名が
                                "Test"で始まるか、"Test"または"Tests"で終わるクラスのみを内包します。
                                このオプションが繰り返し使われる場合、全てのパターンはORを使って結合されます。
                                （デフォルト：^(Test.*|.+[.$]Test.*|.*Tests?)$）
 -N, --exclude-classname=PATTERN
                             完全修飾名がマッチするクラスのみを除外するための正規表現を提供します。
                                このオプションが繰り返し使われる場合、全てのパターンはORを使って結合されます。
     --include-package=PKG   テスト実行に含まれるパッケージを提供します。このオプションは繰り返し可能です。
     --exclude-package=PKG   テスト実行から除外するパッケージを提供します。このオプションは繰り返し可能です。
 -t, --include-tag=TAG       タグがマッチするテストのみを内包するためのタグ、またはタグ表現を提供します。
                                このオプションが繰り返し使われる場合、全てのパターンはORを使って結合されます。
 -T, --exclude-tag=TAG       タグがマッチするテストのみを除外するためのタグまたはタグ表現を提供します。
                                このオプションが繰り返し使われる場合、全てのパターンはORを使って結合されます。
 -e, --include-engine=ENGINE テスト実行で内包するエンジンのIDを提供します。このオプションは繰り返し可能です。
 -E, --exclude-engine=ENGINE テスト実行から除外するエンジンのIDを提供します。このオプションは繰り返し可能です。
     --config=KEY=VALUE      テスト発見・実行のための設定パラメータをセットします。
                                このオプションは繰り返し可能です。
----

[[running-tests-console-launcher-argument-files]]
==== 引数ファイル (@-files)
いくつかのプラットフォーム上では、多くのオプションや長すぎる引数でコマンドラインを
生成する際、コマンドラインの長さに対するシステム制限に遭遇するかもしれません。

バージョン1.3以降では、 `ConsoleLauncher` は _引数ファイル_
（または _@-files_ としても知られています）をサポートするようになります。
引数ファイルはコマンドに渡される引数を自身に含むファイルです。
基礎となる https://github.com/remkop/picocli[picocli]
コマンドライン・パーサーが 文字 `@` で始まる引数に遭遇した時、
そのファイルの中身を引数リストに拡張します。

ファイル内の引数は、スペース、または改行によって分割できます。
もし引数が組み込み空白文字を含む時、引数全体はダブル、もしくはシングルクォテーションで
囲むべきです -- 例えば、 `"-f=My Files/Stuff.java"` のようにです。

もし引数ファイルが存在しない、もしくは読み込み不可の場合、引数は文字通り扱われ、削除されません。
これは恐らく"マッチしない引数"エラーメッセージという結果になるでしょう。
そのようなエラーに対しては、システム・プロパティを `DEBUG` に設定した
`picocli.trace` コマンドを実行することでトラブルシューティングができます。

複数の _@-files_ はコマンドライン上で特定できます。
特定するパスは、現在のディレクトリからの相対パスか、絶対パスです。

最初に `@` のついたパラメータを渡すには、さらに `@` シンボルを追加することでエスケープできます。
例えば、 `@@somearg` は `@somearg` となり、拡張の対象となりません。

[[running-tests-junit-platform-runner]]
=== JUnit 4を用いてJUnit Platformを実行

`JUnitPlatform` ランナーは、JUnit 4ベースの `Runner` であり、
JUnit 4環境内のJUnit Platform上でサポートされているプログラミングモデルを持つ
テスト（例えば、JUnit Jupiterテストクラス）は全て実行できます。

`@RunWith(JUnitPlatform.class)` をクラスに付与することで、
JUnit 4をサポートしているもののJUnit Platformはまだサポートしていない
IDEやビルドシステムであっても実行できます。

NOTE: JUnit PlatformはJUnit 4にはない特徴を持っているので、
そのランナーはJUnit Platformのサブセットのみをサポートしています。
特に、レポート機能についてが当てはまります（  <<running-tests-junit-platform-runner-technical-names, 表示名vs技術的な名称>> をご覧ください）。
しかし、さしあたり `JUnitPlatform` ランナーはとっかかりやすい方法です。

[[running-tests-junit-platform-runner-setup]]
==== セットアップ

次のアーティファクトとそれらの依存関係がクラスパス上に必要です。
グループIDやアーティファクトID、バージョンに関する詳細は <<dependency-metadata, 依存関係のメタデータ>> をご覧ください。

===== 明示的な依存関係

* _test_ スコープ内の `junit-platform-runner` : `JUnitPlatform` ランナーの位置
* _test_ スコープ内の `junit-{junit4-version}.jar` : JUnit 4を用いたテスト実行
* _test_ スコープ内の `junit-jupiter-api` :  `@Test` などを含むJUnit Jupiterを用いてテストを書くためのAPI
* _test runtime_ スコープ内の `junit-jupiter-engine` : JUnit Jupiterのための`TestEngine`実装

===== 推移的な依存関係

* _test_ スコープ内の `junit-platform-suite-api`
* _test_ スコープ内の `junit-platform-launcher`
* _test_ スコープ内の `junit-platform-engine`
* _test_ スコープ内の `junit-platform-commons`
* _test_ スコープ内の `opentest4j`

[[running-tests-junit-platform-runner-technical-names]]
==== 表示名 vs. 技術的な名称

`@RunWith(JUnitPlatform.class)` を通して実行するクラスに
カスタム _表示名_ を定義するには、単に `@SuiteDisplayName` を
クラスに付与してカスタム値を提供するだけです。

デフォルトでは、 _表示名_ はテスト生成物のために使われます。
しかしながら、GradleやMavenといったビルドツールでテスト実行するために
`JUnitPlatrform` ランナーが使われる場合、生成されたテストレポートはしばしば、
テストクラス名や特殊文字を含むカスタム表示名のような短い表示名の代わりに、
テストアーティファクトの _技術的な名称_ （例えば、完全修飾クラス名）を含む必要があります。
レポート目的のために技術的な名称を有効化するには、
単に `@RunWith(JUnitPlatform.class)` と一緒に
`@UseTechnicalNames` アノテーションを宣言するだけです。

`@UseTechnicalNames` の存在は、 `@SuiteDisplayName` を通して設定された
いかなるカスタム表示名も上書きすることに注意してください。

[[running-tests-junit-platform-runner-single-test]]
==== 単一のテストクラス

`JUnitPlatform` ランナーを使う1つの方法は、
テストクラスに直接 `@RunWith(JUnitPlatform.class)` を付与することです。
次の例にあるテストメソッドは `org.junit.Test` （JUnit Vintage）ではなく、
`org.junit.jupiter.api.Test` （JUnit Jupiter）が付与されていることに注意してください。
さらにこの場合では、テストクラスは `public` でないといけません。
そうでないと、IDEやビルドツールがJUnit 4のテストクラスとして認識しない恐れがあります。

[source,java]
----
import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.runner.RunWith;

@RunWith(JUnitPlatform.class)
public class JUnit4ClassDemo {

    @Test
    void succeedingTest() {
        /* no-op */
    }

    @Test
    void failingTest() {
        fail("Failing for failing's sake.");
    }

}
----

[[running-tests-junit-platform-runner-test-suite]]
==== テストスイート

複数のテストクラスがある場合、次の例のようにテストスイートを作成できます。

[source,java]
----
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectPackages;
import org.junit.platform.suite.api.SuiteDisplayName;
import org.junit.runner.RunWith;

@RunWith(JUnitPlatform.class)
@SuiteDisplayName("JUnit 4 Suite Demo")
@SelectPackages("example")
public class JUnit4SuiteDemo {
}
----

`JUnit4SuiteDemo` は、 `example` パッケージとそのサブパッケージ内にある
全てのテストを発見・実行します。デフォルトでは、 `Test` で始まるか、 `Test`
または `Tests` で終わる名前を持つテストクラスのみが含まれます。


.追加的な設定オプション
NOTE:  `@SelectPackages` だけでなく、テスト発見・フィルタリング用の
多くの設定オプションがあります。詳細については、 {javadoc-root}/org/junit/platform/suite/api/package-summary.html[Javadoc]をご覧ください。

[[running-tests-config-params]]
=== 設定パラメータ

どのテストクラスとテストエンジンを内包するか、どのパッケージをスキャンするか、
などをプラットフォームに知らせるのに加えて、特定のテストエンジンや登録した拡張を
指定するための追加的なカスタム設定パラメータの提供が必要な場合があります。
例えば、JUnit Jupiter `TestEngine` は次のユースケースのための _設定パラメータ_ を
サポートしています。

* <<writing-tests-test-instance-lifecycle-changing-default, デフォルトのテストインスタンス・ライフサイクルを変更する>>
* <<extensions-registration-automatic-enabling, 拡張自動検出を有効化する>>
* <<extensions-conditions-deactivation, 条件を無効化する>>

_設定パラメータ_ はテキストベースのキーバリューペアで、
次の仕組みの内の1つを通してJUnit Platform上で実行している
テストエンジンに供給されます。

. `LauncherDiscoveryRequestBuilder` 内に実装されている
    `configurationParameter()` と `configurationParameters()` メソッドは、
    <<launcher-api, `Launcher` API>> に供給されるリクエストを構築するために使われます。
    JUnit Platformによって提供されているツールの内の1つを通じてテスト実行している場合、
    次のように設定パラメータを指定できます。
* <<running-tests-console-launcher,コンソール・ラウンチャー>> ： `--config` コマンドラインオプションを利用。
* <<running-tests-build-gradle-config-params,Gradle>> ：
    `systemProperty` 、または `systemProperties` のDSLを利用。
* <<running-tests-build-maven-config-params,Maven Surefire provider>> ：
    `configurationParameters` プロパティを利用。
. JVMシステムプロパティ。
. JUnit Platform設定ファイル： `junit-platform.properties` という名前で
    クラスパスのルートに置かれたJavaの `Properties` ファイルの構文規則に従ったファイル。

NOTE: 設定パラメータは上で定義された順序で探索されます。結果として、 `Launcher` に直接供給された設定パラメータは、システムプロパティと設定ファイルを通して供給されたパラメータよりも優先して使われます。同じように、システムプロパティを通して供給された設定パラメータは、設定ファイルを通して供給された設定パラメータよりも優先して使われます。

[[running-tests-tag-expressions]]
=== タグ表現

タグ表現は、ブーリアン（boolean）表現で、
`!` と `&` 、 `|` オペレータが使われます。
さらに、 `(` と `)` もオペレータの優先順位を調節するために使われます。

.表1. オペレータ（優先順位の降順）
[cols="^,^,^"]
|===
|オペレータ |意味 |結合性

|! |not |右
|&amp; |and |左
|&#124; |or |左
|===

いくつかの観点でテストにタグ付けしている場合、タグ表現は実行するテストの選択を助けてくれます。
テストタイプ（例えば、 _micro_ や _integration_ 、 _end-to-end_ ）や
特徴（ *foo* や *bar* 、 *baz* ）によってタグ付けするときは、
次のタグ表現が役に立つでしょう。

[cols="^,^"]
|===
|タグ表現 |選択

|foo | *foo* の全てのテスト
|bar \| baz | *bar* の全てのテストに加えて *baz* の全てのテスト
|bar & baz | *bar* と *baz* の積集合となる全てのテスト
|foo & !end-to-end | *foo* のうち、 *end-to-end* でない全てのテスト
|(micro \| integration) & (foo \| baz) | *foo* または *baz* のうち、 *micro* または *integration* である全てのテスト
|===

[[running-tests-capturing-output]]
=== 標準出力 / エラーの捕捉

バージョン1.3以降、JUnit Platformは `System.out` と `System.err` に
プリントされる出力を捕捉するためのオプトイン・サポートを提供しています。
有効化するには、単純に `junit.platform.output.capture.stdout` と/もしくは
`junit.platform.output.capture.stderr` の <<running-tests-config-params, configuration parameter>>
に対して、 `true` を設定するだけです。
さらに、 `junit.platform.output.capture.maxBuffer` を用いて、
実行されるテスト、もしくはコンテナごとに使われるバッファーの最大バイト数を設定できます。

もし有効化している場合、JUnit Platformは対応する出力を捕捉し、
それを `stdout` 、もしくは `stderr` キーを用いるレポートエントリとして、
全ての登録された `{TestExecutionListener}` に対して、
テスト、もしくはコンテナが終了したとレポートされる前に即座に発行します。

捕捉された出力は、テスト、もしくはコンテナを実行するのに使われたスレッドから
発行されたもののみを含むことに注意してください。
他のスレッドによる出力はいずれも省かれます。
なぜなら、特に <<writing-tests-parallel-execution, テストを並行実行する>> 時には、
出力を特定のテストかスレッドと結びつけることは不可能であろうからです。

WARNING: 出力の捕捉は現在 _実験的な_　機能です。これを試して、フィードバックを
JUnit チームに提供することで、彼らはこの機能を改善し、
結果的に <<api-evolution, 昇格>> させることができます。